import {
  Shield,
  Bomb,
  Crosshair,
  Flame,
  Swords,
  Waves,
  Factory,
  HeartPulse,
  Users,
  Landmark,
  Wifi,
  Anchor,
  TrendingDown,
  Leaf,
  Radiation,
  Plane,
  Eye,
  Lock,
  AlertTriangle,
  Ship,
  Megaphone,
  Flag,
  Home,
  Hexagon,
} from 'lucide-react';

const ICON_MAP = {
  shield: Shield,
  bomb: Bomb,
  crosshair: Crosshair,
  flame: Flame,
  swords: Swords,
  waves: Waves,
  factory: Factory,
  'heart-pulse': HeartPulse,
  users: Users,
  landmark: Landmark,
  wifi: Wifi,
  anchor: Anchor,
  'trending-down': TrendingDown,
  leaf: Leaf,
  radiation: Radiation,
  plane: Plane,
  eye: Eye,
  lock: Lock,
  'alert-triangle': AlertTriangle,
  ship: Ship,
  megaphone: Megaphone,
  flag: Flag,
  home: Home,
};

export function getLayerIcon(name) {
  return ICON_MAP[name] || Hexagon;
}
